name: Build Nightly Docker Image

on:
  schedule:
    - cron: '0 17 * * *'
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-images:
    strategy:
      matrix:
        arch_config:
          - {arch: 'arm64'}
          - {arch: 'amd64'}
        image_config:
          - type: 'backend'
            dockerfile: './docker/Dockerfile'
            image_name: nimtable
          - type: 'frontend'
            dockerfile: './docker/Dockerfile.frontend'
            image_name: nimtable-web
    runs-on: ${{ matrix.arch_config.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image (${{ matrix.image_config.type }})
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.image_config.dockerfile }}
          push: false
          load: true
          tags: ${{ matrix.image_config.image_name }}:nightly-${{ github.sha }}-${{ matrix.arch_config.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
